name: adbot-env
channels:
  - defaults
  - conda-forge
dependencies:
  - category_encoders=2.6.3
  - holidays=0.48
  - lightgbm=4.3.0
  - matplotlib=3.8.4
  - notebook=7.2.0
  - numpy=1.26.4
  - pandas=2.2.2
  - pip=24.0
  - pyarrow=16.1.0
  - python=3.12.3
  - scikit-learn=1.4.2
  - seaborn=0.13.2
  - shap=0.45.1
  - pip:
      - polars==0.20.26
